name: lang-t-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - notebook
  - ipywidgets
  - pillow
  - tqdm
  - pip:
    - tensorflow
    - keras
